// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw7qXS9HgVMVn9PcuGqtDl6eUlIeITGls',
    appId: '1:235037919850:web:b752643f55134888059813',
    messagingSenderId: '235037919850',
    projectId: 'proyecto-final-pm',
    authDomain: 'proyecto-final-pm.firebaseapp.com',
    storageBucket: 'proyecto-final-pm.appspot.com',
    measurementId: 'G-PNM6E1V600',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp6thW4w1C58_3whEvB319KSV1SS9N5to',
    appId: '1:235037919850:android:88577d2e236c2950059813',
    messagingSenderId: '235037919850',
    projectId: 'proyecto-final-pm',
    storageBucket: 'proyecto-final-pm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-5qvg2m83wkA3VeEHeBWcrQ7Rq6Ov5wA',
    appId: '1:235037919850:ios:99522af6570dd038059813',
    messagingSenderId: '235037919850',
    projectId: 'proyecto-final-pm',
    storageBucket: 'proyecto-final-pm.appspot.com',
    iosClientId: '235037919850-0f79qj2g9n8l5jkm0a38i2fvdctekha3.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoFinalPm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-5qvg2m83wkA3VeEHeBWcrQ7Rq6Ov5wA',
    appId: '1:235037919850:ios:99522af6570dd038059813',
    messagingSenderId: '235037919850',
    projectId: 'proyecto-final-pm',
    storageBucket: 'proyecto-final-pm.appspot.com',
    iosClientId: '235037919850-0f79qj2g9n8l5jkm0a38i2fvdctekha3.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoFinalPm',
  );
}
